upload:
     repository: /home
     prefixUrl: http://www.baidu.com/
     supportFormat: apk
db:
     driver: com.mysql.jdbc.Driver
     url: jdbc:mysql://api.ennwifi.cn:8000/mapway-wiki
     user: mapway-wiki
     password: mapway-wiki
     schema: mapway-wiki
mail:
    hostName: smtp.163.com
    smtpPort: 25
    userName: jianshez2003@163.com
    password: wangmingli06
    sSLOnConnect: false
    from: jianshez2003@163.com
    fromName: WIKI管理员
    charset: UTF-8
    adminEmail: zhangjsf@enn.cn
spring:
   mvc:
     view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp 
   http:
      multipart:
        max-file-size: 500Mb
        max-request-size: 500Mb 
   metrics:
      export:     
        enabled: false